import json
from pathlib import Path

class JobDescriptionProductPipeline:

    def __init__(
        self,
        settings,
        classifier,
        file_reader,
        file_writer,
        file_mover,
        json_input_dir,
        json_output_dir,
        json_processed_dir
    ):
        self.settings = settings
        self.classifier = classifier
        self.file_reader = file_reader
        self.file_writer = file_writer
        self.file_mover = file_mover
        self.json_input_dir = json_input_dir
        self.json_output_dir = json_output_dir
        self.json_processed_dir = json_processed_dir

    def process_all_files(self):
        # Scan for existing JSON inputs generated by your raw JD process
        input_path = Path(self.json_input_dir)
        json_files = list(input_path.glob("*.json"))
        
        print(f"\n📂 Found {len(json_files)} extracted JD JSON files to parse for products")

        for index, file_path in enumerate(json_files, 1):
            print("\n" + "=" * 70)
            print(f"🛠️ Isolating products ({index}/{len(json_files)}): {file_path.name}")
            self._process_single_json(file_path)

        print("\n🎉 Product identification pipeline execution finished successfully.")

    def _process_single_json(self, file_path: Path):
        try:
            # 1. Read the existing structured JD JSON
            with open(file_path, "r", encoding="utf-8") as f:
                raw_json_str = f.read()

            # 2. Query LLM to clean, translate, and classify raw tech tokens into strict items
            product_json_data = self.classifier.classify(raw_json_str)

        except Exception as e:
            print(f"❌ Failed parsing or querying LLM for file {file_path.name}: {e}")
            return

        try:
            # 3. Write structured classification data to the new product directory
            output_file = Path(self.json_output_dir) / file_path.name
            
            # Ensure the directory exists dynamically
            output_file.parent.mkdir(parents=True, exist_ok=True)
            
            self.file_writer.write_text(
                output_file, 
                json.dumps(product_json_data, indent=2)
            )
            print(f"✅ Extracted Product Schema Saved: {output_file}")

        except Exception as e:
            print(f"❌ Failed to write product JSON output: {e}")
            return

        try:
            # 4. Move processed raw file down the queue stream to avoid duplicate runtime loops
            destination_dir = Path(self.json_processed_dir)
            destination_dir.mkdir(parents=True, exist_ok=True)
            
            destination = self.file_mover.move_file(
                file_path,
                str(destination_dir)
            )
            print(f"📦 Archived Raw JD file out of entry point: {destination}")

        except Exception as e:
            print(f"❌ Failed to move raw processed JD to destination directory: {e}")